##Spring Configuration
server:
  port: 9090
spring:
  application:
    name: retries-dlq-strategy
  devtools:
    add-properties: false

app:
  async:
    withDLQRetry: true
    retryDelay: 5000
    maxRetries: 3


